services:
  todo-api:
    build:
      context: .
    ports:
      - "8080:8080"
    networks:
      - monitoring

  database:
    image: postgres:17-alpine
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - monitoring
      
  prometheus:
    image: prom/prometheus:v3.4.1
    container_name: prometheus
    ports:
    - 9090:9090
    volumes:
    - ./prometheus.yml:/etc/prometheus/prometheus.yml
    - prometheus_data:/prometheus
    command:
    - --config.file=/etc/prometheus/prometheus.yml
    networks:
      - monitoring
    
volumes:
  postgres_data:
    driver: local
  prometheus_data:
    driver: local

networks:
  monitoring:
    driver: bridge
  